name: Staging Web Deploy

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag Name (ex : v0.0.1)'
        required: true

jobs:
  build_push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tags }}

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: adirah/learning:${{ github.event.inputs.tags }} , adirah/learning:latest

  deploy_to_vps:
    name: deploy to vps
    runs-on: ubuntu-latest
    needs: [build_push_to_registry]
    steps:
      - name: ssh to vps
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            docker stop $(docker ps | grep -i 5000 | awk '{print $1}')
            docker rmi --force adirah/learning:latest
            docker pull adirah/learning:latest
            docker run -p 5000:80 -d adirah/learning:latest